spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/codeagent
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

anthropic:
  api-key: API key

claude:
  model: claude-sonnet-4-20250514
